name: My Pipeline              # any name you want

on:
  push:
    branches: [main]           # trigger on push to main

jobs:
  job_one:                     # first job name
    runs-on: ubuntu-latest     # always this
    steps:
      - uses: actions/checkout@v4   # ALWAYS first step

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install
        run: pip install -r requirements.txt
