name: ML Training Pipeline
on:
  push:
  branches: [main]
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup@v4
       with:
       python-version: '3.10'
      - name: install
        run: pip install -r requirements.txt mlflow
      - name: train and ml flow
        env:
          mlflow_tracking_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: python train.py
